### ISSUE TITLE
problème de déploiement sur tomcat 8

### ISSUE THREAD

**Issue by vwilliam** [lefevre00/parking#102]
Voici l'erreur qui est apparu lors du déploiement sur un serveur TOMCAT8 de la mutuelle : 

Jul 20, 2016 10:50:27 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat8/webapps/parking.war
Jul 20, 2016 10:50:29 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Jul 20, 2016 10:50:29 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error filterStart
Jul 20, 2016 10:50:29 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/parking] startup failed due to previous errors
Jul 20, 2016 10:50:29 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat8/webapps/parking.war has finished in 1,950 ms

Michael, as tu eu ce soucis lors de tes tests en local ?

**Comment by lefevre00** [comment]
J'ai eu ces erreurs, mais n'ai rien fait de special quand a cela.
J'ai surtout chercher a faire la connection a postgres, et definit des users dans tomcat pour admin des applis.
Est-ce que le war est ok, qd vous le dezipper ? (web.xml ...)

**Comment by vwilliam** [comment]
Je viens de faire avec succès la configuration tomcat8 / postgres sur mon post et j'ai le message dans la log mais c'est juste une info...

**Comment by lefevre00** [comment]
Je viens de lancer tomcat, j'ai l'erreur TLD mais ca marche.

**Comment by vwilliam** [comment]
Deploiement ok. Problème de version de tomcat avec la distrib Linux.
