### ISSUE TITLE
Application hackée.

### ISSUE THREAD

**Issue by vwilliam** [lefevre00/parking#106]
Guillaume bertin a trouvé une faille permettant de réserver une place sur plus de temps que 2 jours.
Il modifie la date de réservation directement via l'url...
![sans-titre](https://cloud.githubusercontent.com/assets/11461653/17176935/3ac4524a-540f-11e6-9c30-18e0536f5f87.png)

**Comment by vwilliam** [comment]
J'ai retrouvé le hacké et sous la torture il m'a divulgué la faille.
Il utilise l'url lors de la recherche et modifie la date directement 

http://takemyplace.herokuapp.com/protected/search?day=2016-07-29

**Comment by lefevre00** [comment]
Forcer la prise en compte uniquement de rêquete en POST sur cette page ?
