### ISSUE TITLE
Erreur 500 Statistiques

### ISSUE THREAD

**Issue by atamd** [lefevre00/parking#112]
Erreur 500 quand on clique sur btn pour visualiser les statistiques (côté administration) !
Uniquement sur les serveurs Tomcat distants. 
Je n'ai pas d'erreur sur mon Tomcat local !!!!

**Comment by atamd** [comment]
Le pb vient lors de la manipulation de la session.
En effet, l'administrateur n'existe pas en base. Ses données sont stockées dans un fichier de properties.
Donc lors de la connexion, le user créé n'a pas d'ID (user_id = null) qui est utilisé dans la session.

**Comment by lefevre00** [comment]
Il serait plus simple de créer l'admin en base, avec une colonne isAdmin sur le user.
Pas de gestion de l'authentification.
Présentation des menus selon le type :
- admin
- avec place
- sans place

**Comment by lefevre00** [comment]
Je déplace l'évol dans une autre issue.

**Comment by atamd** [comment]
Je pense que cette issue avait été cloturée !
Le pb avait été réglé, tout simplement, par la création, d'un compte admin en base.
