### ISSUE TITLE
Peut-on fusionner standalone dans master ?

### ISSUE THREAD

**Issue by lefevre00** [lefevre00/parking#114]
Ouvert à discussion, vous pouvez le faire si vous voulez.

**Comment by vwilliam** [comment]
A confirmer avec Abdel mais je pense que c'est possible.

**Comment by lefevre00** [comment]
Ok, faites un retour quand c'est OK

**Comment by atamd** [comment]
Pour moi, c'est oui

**Comment by lefevre00** [comment]
Done
