### ISSUE TITLE
Init db depending on platform

### ISSUE THREAD

**Issue by lefevre00** [lefevre00/parking#4]
Running on heroku (pg) or localhost (h2),
- Create table structure (both)
- Insert testing data (h2)

**Comment by lefevre00** [comment]
Peux-tu voir a ne pas faire des insert dans Application, mais dans StartParking plutôt.
Uniquement pour les tests en local, et pas lorsqu'on deploie sur heroku.

**Comment by vwilliam** [comment]
Désolé pas trop le temps d'y travailler cette semaine. J'ai rien commit sur ma branche...
