### ISSUE TITLE
A la réinitialisation du mot de passe, on tombe sur une "500 Internal Error" 

### ISSUE THREAD

**Issue by guilhemrostain** [lefevre00/parking#51]

**Comment by lefevre00** [comment]
- [qtp123331195-15] ERROR spark.webserver.MatcherFilter -
  » 20 Apr 2016 20:16:11.462 154 <190>1 2016-04-20T18:16:11.130088+00:00 app web.1 - - java.lang.IllegalArgumentException: Hashed password required
  » 20 Apr 2016 20:16:11.462 180 <190>1 2016-04-20T18:16:11.130254+00:00 app web.1 - - at org.friends.app.service.impl.UserServiceBean.setPassword(UserServiceBean.java:183)
  » 20 Apr 2016 20:16:11.462 178 <190>1 2016-04-20T18:16:11.130358+00:00 app web.1 - - at org.friends.app.view.route.PasswordTokenRoute.handle(PasswordTokenRoute.java:35)
  » 20 Apr 2016 20:16:11.462 165 <190>1 2016-04-20T18:16:11.130576+00:00 app web.1 - -
