### ISSUE TITLE
Schema des tables

### ISSUE THREAD

**Issue by atamd** [lefevre00/parking#6]
Je propose le schéma suivant :
- Table Salarie : 
- idSalarie : Integer autoincrement (non null)
- Nom : String (non null)
- Prenon : String (non null)
- NumPlace : Integer
- Email AMDM : String (non null)
- Email Perso : String (1) 
- Numero Portable : String (2)
- Mot de passe : (non null)
- canal de notification : (1) ou (2)

La table salarié doit être pré-alimentée avec la liste des salariés disposant d'une place à Mezzo
- Table PlacesDispos :
- NumPlace : Integer (non null)
- Jour : Date
- OccupePar : IdSalarié

**Comment by lefevre00** [comment]
J'aime la notion d'utilisateur plus que de salarié car le site n'est pas corporate.
Le type d'utilisateur viendra du fait qu'il a ou non une place atitrée.

**Comment by lefevre00** [comment]
Je regarde pour modeliser de la base postgres en dehors de l'application, via un outil pdadmin3.

Ainsi, la base ne sera pas altérée par l'application sauf en mode test car nous utilisons H2.

**Comment by lefevre00** [comment]
La description des tables est dans un fichier init_db.sql.
Il faut la retravailler pour être utilisée au chargement de h2.
