### ISSUE TITLE
Libellé des boutons de réservation

### ISSUE THREAD

**Issue by vwilliam** [lefevre00/parking#66]
Dans la page de réservation, les libellés des boutons sont "réserver aujourd'hui" "réserver demain".

Les libellés ne correspondent pas avec les dates de réservation. En effet après 18h, on propose de réserver pour la journée suivante (et non aujourd'hui) et pour la journée dur surlendemain (et non demain) (Idem psi l'on accède à l'application pendant le week-end.

Proposition : mettre Réserver une place le Mercredi jj/mm/aaa

**Comment by lefevre00** [comment]
Si l'on affiche "reserver le 12/3/2016" et "reserver le 13/3/2016", présenter également la date du jour.
Exemple :
"Nous sommes le 11/3/2016"
Puis les boutons réserver

**Comment by atamd** [comment]
Pourquoi ne pas garder les boutons actuels et pour le week-end afficher "lundi".
Pour enfoncer le clou, ne searit-il pas intéressant de créer une table "JoursFermetures" par exemple dans laquelle on met les jours de fermetures (férié, pont...)

**Comment by lefevre00** [comment]
La remarque d'Abdel peut faire l'object d'une autre issue.
