### ISSUE TITLE
Création d'un compte

### ISSUE THREAD

**Issue by atamd** [lefevre00/parking#7]
Le salarié doit remplir le formulaire en saisissant :
- Nom : donnée obligatoire
- Prénom : donnée obligatoire
- Numéro de la place : donnée non obligatoire
- Email AMDM : obligatoire
- Email perso : non obligatoire (1)
- NumPortable : non obligatoire (2)
- Mot de passe : obligatoire
- Canal de notification : (1) ou (2)

A la validation, si numéro de la place est renseigné, on vérifie que le nom/prénom sont bien dans la table salarié qui est pré-alimentée avec les noms des salariés disposant d'une place à Mezzo.

Si le numéro de la place n'est pas renseigné, il faut alors envoyer un mail via le mail AMDM pour valider la création du compte

**Comment by lefevre00** [comment]
Pour commencer dans la simplicité, voyons a proposer seulement l'adresse amdm. Cela permettra à un éventuel admin de controler les utilisateurs.

Idem pour le portable, c'est un fonctionnalité qui pourrait être ajouter par la suite.

**Comment by lefevre00** [comment]
Peut-on clore cette issue  ? La creation marche avec données limitées.
On peut en créer une autre pour ajouter d'autres données.
