### ISSUE TITLE
Bug dans la réservation

### ISSUE THREAD

**Issue by vwilliam** [lefevre00/parking#70]
Je suis un utilisateur avec une place attribuée.
Je libère mes 2 places pour les jours X et Y. Personne ne les réserve
Je vais dans la page réservation et j'ai la possibilité de réserver une place qui n'est pas la mienne pour le jour X...
Le bouton réservation le jour X dans la page réservation doit être à l'état disable

**Comment by lefevre00** [comment]
Pbm ligne PlaceServiceBean:228

**Comment by vwilliam** [comment]
J'ai eu de nouveau le soucis dans les mêmes conditions excepté que la place Y a été réservée par quelqu'un entre temps...
