### ISSUE TITLE
Make Logout page a authenticated one.

### ISSUE THREAD

**Issue by lefevre00** [lefevre00/parking#81]
It doesn't have any sense to logout if not authenticated.

**Comment by atamd** [comment]
?????

2016-05-11 22:34 GMT+02:00 Michaël Lefèvre notifications@github.com:

> It doesn't have any sense to logout if not authenticated.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lefevre00/parking/issues/81

## 

_"Tais-toi, et tu éviteras le danger ; Écoute, et tu apprendras."_

**Comment by lefevre00** [comment]
Ben oui, si t'es pas signé, alors tu ne devrait pas aller sur cette url.
Donc si tu y vas sans être signé -> on te redirige vers le login.

**Comment by guilhemrostain** [comment]
Hey ça serait pas mal aussi que la déconnexion redirige sur le login plutôt que de rester sur la page "vous êtes déconnecté"

**Comment by atamd** [comment]
Oui, on peut faire une redirection automatique après 5 secondes par exemple :
&lt; meta http-equiv="refresh" content="5; URL=index.ftl" &gt;

**Comment by atamd** [comment]
<meta http-equiv="refresh" content="5; URL=index.ftl">
