### ISSUE TITLE
Comment deployer l'application sur un autre serveur qu'heroku

### ISSUE THREAD

**Issue by vwilliam** [lefevre00/parking#98]
Log de Stephen après une tentative de construction d'un war 

[INFO] Packaging webapp
[INFO] Assembling webapp [parking] in [/Users/unreal/Downloads/parking-stable-fix/target/parking-1.1]
[INFO] Processing war project
[INFO] Webapp assembled in [402 msecs]
[INFO] Building war: /Users/unreal/Downloads/parking-stable-fix/target/parking-1.1.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.429 s
[INFO] Finished at: 2016-07-06T17:36:29+02:00
[INFO] Final Memory: 19M/273M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project parking: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lefevre00** [comment]
Pour l'instant, il s'agit d'une application a part entière.
Le framework SparkJava inclus Jetty et se lance en ecoutant sur un port.
Ce n'est pas un war que l'on dépose dans tomcat/jboss.

Heroku, apres avoir fait un build maven, lance la commande :
`java -cp target/classes:target/dependency/* Main`

Sinon faut voir à faire un fat-jar lancé avec
`java -jar parking.jar`

**Comment by lefevre00** [comment]
Sinon, mettre en place qqch comme :
http://sparkjava.com/documentation.html#other-webserver

Pour les tests, on peut rester sur le jetty embarqué.

**Comment by lefevre00** [comment]
Via des targets maven différentes, on peut déployer en jar sur Heroku (pour tests) et en war pour un serveur interne.
Voir, avoir un structure de projet en modules :
- war (parent)
- serveur (logique)
- client (front sparkjava)

**Comment by jolisylvain** [comment]
Le war est bien généré mais son déploiement échoue sous un tomcat 8 car il n'arrive pas à initialiser la session Hibernate (ce qui ne m'etonne quà moitié vu que je n'ai pas de Postgres sur mon poste)

**Comment by lefevre00** [comment]
Pour tester, tu peux voir a positionner la dépendance vers h2 sans le scope "test", et utiliser la variable d'environnement pour forcer l'usage de h2.
Voir l'appel : `System.setProperty(Configuration.DEPLOY_MODE, "dev");`

Regarder la classe Configuration qui fournit l'url de connection.
Cela sera déporter dans la conf du tomcat (si lancer sous tomcat).

Pour le lancement sur heroku, faut toujours taper sur postgresql.
Si le support d'heroku devient pesant, mais c'est de la conf, faut commenter.

**Comment by jolisylvain** [comment]
Pour déployer l'application sur un poste de dév, ça serait pas mal mais on cherchait surtout à se connecter à un postgres installé sur un serveur. Je crois que willy voulait tester ça demain. Plus de news très bientôt donc :-)

**Comment by lefevre00** [comment]
Je connecte chez moi. Donc je close.
